### PR TITLE
Icon mask to bounds

### PR DESCRIPTION
**Pull request by MamtaKukreja**

### CODE REVIEW

**Comment by MamtaKukreja** [comment]
@zekunyan Please have a look at this pull request

**Comment by zekunyan** [comment]
@MamtaKukreja It's not a common feature.

**Comment by MamtaKukreja** [comment]
@zekunyan Even though it's not a common feature, it makes this library easily customizable. So I request you to have a look at it once again .

**Comment by zekunyan** [comment]
@MamtaKukreja The `cornerRadius` property is used for the whole snackbar view. And `maskedCorners` has four types of mask. Now the `isIconMasked` function can only meet your needs. It's not customizable for others. I can not allow this happen.

**Comment by MamtaKukreja** [comment]
@zekunyan Thanks for your response.

How about customizing it to have properties for all the four masks of `maskedCorners`?
Or can we make the imageView accessible outside the file so that it can be customized by all?

Please share your views so that I can make changes accordingly.

**Comment by zekunyan** [comment]
@MamtaKukreja "Make the imageView accessible outside" is a better idea. And the title label and action button can also be accessible outside too.

**Comment by MamtaKukreja** [comment]
Thanks @zekunyan . I have made the imageView accessible now. Please review again.

**Comment by MamtaKukreja** [comment]
Hi @zekunyan , please have a look at the new changes in this PR.

**Comment by zekunyan** [comment]
@MamtaKukreja There should be a better way to do this and i will do it myself later.

**Comment by zekunyan** [comment]
@MamtaKukreja You can access iconImageView in the new version 1.10.0

**Pull request closed without merging**
