### PR TITLE
Allow to only have an icon on action button

### PR DESCRIPTION
**Pull request by kenji21**
Hi, first thank for this component, I've added a small improvement I need to have : usage of an icon for the action button

Added button to the example app to show this
Added var to Snackbar class to allow actionIcon customization

### CODE REVIEW

**Comment by zekunyan** [comment]
Great work !

**Comment by kenji21** [comment]
Thank you, can you make a release (so i'll delete my clone and make my Cartfile point to your repo) 
Maybe it will be 1.7.0 as it is a new feature ?

**Comment by zekunyan** [comment]
@kenji21 It's done.

**Comment by kenji21** [comment]
👍🏻

**Pull request merged**
